language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '5.0'
  - '5.1'
env:
  - CXX=g++-4.8
before_install:
  - sudo apt-get update
  - "mkdir -p ~/.npm"
install:
  - npm install -g node-gyp-install
  - node-gyp-install
  - npm install serialport
  - npm install noble
  - npm install
  - npm install -g grunt-cli istanbul codeclimate-test-reporter
script:
  - grunt lint
  - istanbul cover ./node_modules/.bin/_mocha spec/helper.js spec/lib/*.js spec/lib/**/*.js --report lcovonly -- -R spec
  - CODECLIMATE_REPO_TOKEN=88ec807c5d22e853e1a21b9289233f525e793f09e5e81322899ee519587d3689 codeclimate-test-reporter < coverage/lcov.info
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - g++-4.8-multilib
    - libbluetooth-dev
